### ISSUE TITLE
Swing Integration not working

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#2]
HalcyonSwingNode is not working when allowing an embedded Swing component to be dockable.
Probably a threading issue

![image](https://cloud.githubusercontent.com/assets/1870994/14669663/17e0807c-06ea-11e6-9120-803124aef626.png)

**Comment by hkmoon** [comment]
Please, have a look on my commit RTlib/RTlib@25f801621c7a48684495fdffd808ae7d81269b6d.
Your application entry is from Swing, not native JavaFX. In the near future, let's think about using whole native JavaFX way.
However, when I use JavaFX entry, your 2d/3d displays do not work. ;(

**Comment by royerloic** [comment]
Great! Thanks HongKee! it works...
There is a bit of flickering when resizing... is it possible to reduce that?
Please remove the "Yo" logging... :-)
Great job!

**Comment by hkmoon** [comment]
Hey, this works better RTlib/RTlib@e85c82d8fa51029f69b7bf611684d59e57fbbd2e.
Probably, there must be a better way. ;(

**Comment by royerloic** [comment]
Dear HongKee, 

Right now all the tabs are open when opening the demo,
is this normal? I would prefer that they’d be closed instead…
Where is this controlled?

Thanks!

> On 21 Apr 2016, at 17:39, HongKee Moon notifications@github.com wrote:
> 
> Closed #2 https://github.com/RTlib/Halcyon/issues/2.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/RTlib/Halcyon/issues/2#event-636363050

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/

**Comment by hkmoon** [comment]
It is actually normal. I will make it closed at startup as you wish!

**Comment by hkmoon** [comment]
I committed the better way to handling scripting windows in RTlib/RTlib@d9ec36c224549b80e4c960a054c1dc54480cc724
The change is reverted to your initial solution. Have a look on it when you have time.
Thanks!

**Comment by royerloic** [comment]
It behaves much better! Great Job!

Did see this exception though:

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at javafx.embed.swing.SwingNode.minHeight(SwingNode.java:442)
    at javafx.scene.layout.Region.computeChildMinAreaHeight(Region.java:1697)
    at javafx.scene.layout.BorderPane.getAreaHeight(BorderPane.java:618)
    at javafx.scene.layout.BorderPane.computeMinHeight(BorderPane.java:415)
    at javafx.scene.Parent.minHeight(Parent.java:957)
    at javafx.scene.layout.Region.minHeight(Region.java:1401)
    at javafx.scene.layout.Region.computeChildPrefAreaHeight(Region.java:1762)
    at javafx.scene.layout.VBox.getAreaHeights(VBox.java:440)
    at javafx.scene.layout.VBox.computeContentHeight(VBox.java:518)
    at javafx.scene.layout.VBox.computePrefHeight(VBox.java:417)
    at javafx.scene.Parent.prefHeight(Parent.java:935)
    at javafx.scene.layout.Region.prefHeight(Region.java:1435)
    at org.dockfx.pane.ContentSplitPane.addNode(ContentSplitPane.java:160)
    at org.dockfx.DockPane.dock(DockPane.java:463)
    at org.dockfx.DockNode.dock(DockNode.java:700)
    at halcyon.view.ViewManager.open(ViewManager.java:259)
    at halcyon.view.TreePanel.lambda$0(TreePanel.java:119)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)

**Comment by hkmoon** [comment]
No!!! It shouldn't be!!

**Comment by hkmoon** [comment]
Did you get the latest version of ScriptingWindow?

**Comment by royerloic** [comment]
haaaa... ok

**Comment by royerloic** [comment]
ok, good... works!
